spring:
  application:
    name: discodeit

springdoc:
  api-docs:
    enabled: true          # API 스펙 JSON 활성화
    path: /api-docs        # 스펙 JSON 기본 경로
  swagger-ui:
    enabled: true          # Swagger UI 사용 여부
    path: /swagger-ui.html # Swagger UI 접속 경로
    display-request-duration: true   # 요청 소요 시간 표시
    persist-authorization: true      # 새로고침해도 토큰 유지
